export type Vec3=[number,number,number];
export interface Keyframe{frame:number;value:Vec3;interpolation?:'linear'|'smooth'|'step'}
export interface Material{id:string;name:string;color:string;metalness:number;roughness:number}
export interface MeshData{positions:number[];indices?:number[]}
export interface SceneObject{id:string;name:string;type:string;parent:string|null;visible:boolean;locked:boolean;position:Vec3;rotation:Vec3;scale:Vec3;params:Record<string,number|string|boolean>;material:string|null;modifiers:{type:string;strength:number;enabled?:boolean}[];tracks:Partial<Record<'position'|'rotation'|'scale',Keyframe[]>>;geometry?:MeshData}
export interface Scene{id:string;name:string;format:'astrum';version:1;objects:SceneObject[];materials:Material[];fps:number;duration:number;settings:{background:string;exposure:number;grid:boolean;shadows:boolean}}
export class Signal<T=unknown>{subscribe(fn:(value:T)=>void):()=>void;emit(value:T):void}
export class SceneDocument{constructor(scene?:Scene);scene:Scene;selection:string[];revision:number;undoStack:{label:string;before:Scene;after:Scene}[];redoStack:{label:string;before:Scene;after:Scene}[];changed:Signal<{label:string;scene:Scene}>;selectionChanged:Signal<string[]>;get(id:string):SceneObject|undefined;select(ids:string[]):void;transact(label:string,fn:(scene:Scene)=>void):void;undo():void;redo():void;add(type?:string,extra?:Partial<SceneObject>):SceneObject;update(id:string,patch:Partial<SceneObject>,label?:string):void;remove(ids?:string[]):void;duplicate(ids?:string[]):SceneObject[];reparent(id:string,parent:string|null):void;keyframe(ids?:string[],frame?:number):void;replace(scene:Scene):void;serialize():string;dispose():void}
export const VERSION:string;export const TYPES:string[];export function uid():string;export function clone<T>(value:T):T;export function material(name?:string,color?:string,extra?:Partial<Material>):Material;export function object(type?:string,extra?:Partial<SceneObject>):SceneObject;export function emptyScene():Scene;export function demoScene():Scene;export function validateScene(scene:unknown):Scene;export function sampleTrack(keys:Keyframe[],frame:number):Vec3|null;export function evaluateObject(object:SceneObject,frame:number):SceneObject;export function seededRandom(seed?:number):()=>number;export function cloneTransforms(params?:Record<string,number|string>):{position:Vec3;rotation:Vec3;scale:Vec3}[];export interface Operation{collection:'objects'|'materials'|'meta';id:string;value:unknown}export function diffScenes(base:Scene,next:Scene):Operation[];export function applyOperations(scene:Scene,ops:Operation[]):Scene;
